[package]
name = "devp2p"
version = "0.3.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Ethereum's devp2p protocol implementation in Rust."
repository = "https://github.com/sorpaas/rust-devp2p"
edition = "2018"

[dependencies]
async-trait = "*"
bytes = "*"
discv5 = { git = "https://github.com/sigp/discv5" }
enr = "0.1"
etcommon-bigint = "0.2"
etcommon-block = "0.3"
etcommon-hexutil = "0.2"
etcommon-rlp = "0.2"
ethereum-types = "*"
futures = "0.3"
log = "0.3"
rand = "0.3.12"
rlpx = { version = "0.3", path = "./rlpx" }
secp256k1-plus = "0.5"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
env_logger = "0.3"
sha3 = "0.6"
url = "1.5.1"