[package]
name = "devp2p"
version = "0.3.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Ethereum's devp2p protocol implementation in Rust."
repository = "https://github.com/sorpaas/rust-devp2p"
edition = "2018"

[dependencies]
async-trait = "0.1"
bytes = "0.5"
discv5 = { git = "https://github.com/sigp/discv5" }
enr = "0.1"
ethereum = { git = "https://github.com/rust-blockchain/ethereum" }
ethereum-types = "0.9"
futures = "0.3"
log = "0.4"
rand = "0.7"
rlp = "0.4"
rlpx = { version = "0.3", path = "./rlpx" }
tokio = { version = "0.2", features = ["full"] }
uint = "*"

[dev-dependencies]
env_logger = "0.7"
sha3 = "0.9"
url = "2"